### ISSUE TITLE
Double element with page-title and TOC position

### ISSUE THREAD

**Issue by sowee15** [terryweiss/docstrap#87]
Hi,

When I generate my doc, I get two h1 with class 'page-title'. I think one is coming from layout.tmpl and the other from container.tmpl. Looks like the
````
<h1 class="page-title"><?js= title ?></h1>
````
in layout.tmpl is unnecessary as container.tmpl looks to be in charge of displaying the title.

There is another thing that looked weird, the actual TOC has a fixed position but it has right: 0px : in IE this is weird since the page content shows under the page scrollbar (unless you deactivate the IE scrollbar overlay by adding this to the html element in css):
````
html { -ms-overflow-style: scrollbar; }
```` 

Another solution would be to set it to right: 40px or so.

Thanks for the great work, your project makes the jsdoc much more user friendly and accessible.

**Comment by mwittig** [comment]
See also https://github.com/terryweiss/docstrap/issues/85

**Comment by georgschlenkhoff** [comment]
I see same issue. How to solve it?

**Comment by lukeapage** [comment]
+1. Fixed by https://github.com/terryweiss/docstrap/pull/89 ?

**Comment by gnstanley** [comment]
It seems that #89 had fixed it, but it since been un-fixed: see [this commit](https://github.com/terryweiss/docstrap/commit/c6e9d29307657e34805230818343657e38ca9c42) and my comment in issue #89. 

This should be an easy fix: it should be as simple as removing the line that was [added back in](https://github.com/terryweiss/docstrap/commit/c6e9d29307657e34805230818343657e38ca9c42#diff-1f2e6dffd9f034b975ed415f0220e336R50).

**Comment by mwittig** [comment]
should be re-opened

**Comment by Pringels** [comment]
+1

**Comment by dgreese94** [comment]
+1

**Comment by deltreey** [comment]
+1
